# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-08 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='semester',
            field=models.CharField(choices=[('S1', 'Semester 2'), ('S2', 'Semester 1')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.CharField(choices=[('Y4', 'Year 4'), ('Y3', 'Year 3'), ('Y2', 'Year 2'), ('Y1', 'Year 1')], max_length=2),
        ),
    ]
