# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-08 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0002_auto_20170508_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='semester',
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.CharField(choices=[('Y4S1', 'Year 4 Semester 1'), ('Y4S2', 'Year 4 Semester 2'), ('Y3S1', 'Year 3 Semester 1'), ('Y3S2', 'Year 3 Semester 2'), ('Y2S1', 'Year 3 Semester 1'), ('Y2S2', 'Year 2 Semester 1'), ('Y1S1', 'Year 1 Semester 1'), ('Y1S2', 'Year 1 Semester 2')], max_length=1),
        ),
    ]
