# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-16 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0005_auto_20170508_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aillment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('notes', models.CharField(max_length=1000)),
                ('prescription', models.CharField(max_length=500)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reception.Patient')),
            ],
        ),
    ]
