# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-17 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0007_aillment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aillment',
            name='date',
            field=models.DateTimeField(verbose_name=['%Y-%m-%d %H:%M']),
        ),
        migrations.AlterField(
            model_name='patient',
            name='time',
            field=models.DateTimeField(verbose_name=['%Y-%m-%d %H:%M']),
        ),
    ]
