# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-17 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0008_auto_20170517_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_age',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
