# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-08 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_fname', models.CharField(max_length=30)),
                ('doctor_mname', models.CharField(max_length=30)),
                ('doctor_sname', models.CharField(max_length=30)),
                ('doctor_age', models.IntegerField(max_length=2)),
                ('doctor_id', models.IntegerField(max_length=8)),
                ('doctor_image', models.ImageField(upload_to='/tmp/%Y/%m/%d')),
            ],
        ),
    ]
