# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0002_remove_doctor_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_id',
            field=models.IntegerField(),
        ),
    ]
